### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [emilsharkov/bukvalno#1]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a little bit. If you want to read more about LTO and its possible modes, I recommend starting from [this](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) Rustc documentation.

I think you can enable LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where in addition to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most optimized version of the application. However, if we enable it on the Cargo profile level for the Release profile, users, who install the application with `cargo install` will get the LTO-optimized version of the game "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48). You also could be interested in other optimization options like `codegen-units = 1`, etc.

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41, Rust 1.82, the latest version of the project) - here are the results:
* Release: 3 Mib
* Release + `codegen-units = 1`: 2.7 Mib
* Release + LTO: 2.6 Mib
* Release + `codegen-units = 1` + LTO: 2.5 Mib

Thank you. It would be nice if you would use LTO for your future Rust developments :)

**Comment by emilsharkov** [comment]
Noted thanks. As a side note, why do you evangelize the use of LTO?

**Comment by zamazan4ik** [comment]
> As a side note, why do you evangelize the use of LTO?

I believe that Rust software should be performant ("blazing fast", heh) by default since I prefer to use fast software. Since I use many tools (and more will be used in the future) I want to use such applications in their most optimized way. LTO helps with achieving it. Unfortunately, we are not ready yet to enable LTO somehow by default for the Release profile (or any other additional profile) - this is why I am trying to enable LTO in Rust projects on the Cargo level in upstreams. In this case, users will get LTO-optimized programs by default in many distribution ways: `cargo install`, OS-built versions by maintainers, CI systems.
